### ISSUE TITLE
misdefinition of 'gold OA'

### ISSUE THREAD

**Issue by rossmounce** [sje30/lse#1]
"the publisher-preferred model of 'gold OA' where an article processing charge must be paid"

Gold OA originally meant just OA at the journal. See Suber's book on OA. Gold OA is not synonymous with APC-OA.
https://openaccesseks.mitpress.mit.edu/ 

Technically speaking Diamond OA is a subtype of Gold OA (as in Diamond OA, the output is also made available by the publisher at the official publisher website).

You could argue there has been 'semantic drift' in what 'Gold OA' means, so that a lot of people use it to describe APC-OA but I do not buy that argument. If you want to talk about APC-OA say APC-OA, if you want to talk about outputs being open access at the journal then you can say 'Gold OA' (but this doesnt necessarily mean an APC needs/has been levied) or just 'journal-mediated open access' or 'outputs made open access at the journal'.

**Comment by rossmounce** [comment]
I note your final remarks also are consistent with your interpretation of the meaning of 'gold OA' 

" 'green' or 'gold' is a false dichotomy"

But if you take it as the work is made open access at the journal (gold) or at the repository (green), then I think you'll find it's not so false, albeit it becomes complicated when speaking about overlay journals that overlay on repository deposits - but that's another argument for another audience.  IMHO, the UKRI OA policy clearly maps onto repository mediated OA (Route 2 ; 'green') and journal/publisher mediated OA (Route 1 ; 'gold' but not necessarily with APC)

**Comment by sje30** [comment]
Thanks for these comments; I clearly need to sharpen my understanding of the different terms.  I hadn't thought about diamond as a subset of gold before.  

Is 'APC OA' in common usage yet?

Thanks also for the Suber link; I'll try to ensure I stick to that definition of Green vs Gold.
