### ISSUE TITLE
How many papers will be green OA vs gold OA?

### ISSUE THREAD

**Issue by rossmounce** [sje30/lse#4]
Good section.

My observations on RRS-language at submission + green OA is that it is:

a) economically, it's a safety-valve if the publishers do continue to raise their pricing of open access at the journal options (aka Gold OA)

b) from the author POV, the RRS-language is an excellent safety net. If the authors include the RRS-language at submission they will _always_ be guaranteed to be in compliance with their UKRI research funder open access policy. So even if it's not strictly mandated it would certainly be advisable for authors to do it. If the publisher raises concerns about the RRS-language then it might signal some 'red flag' issues and it serves to notify potential issues with how the publisher intends to proceed.

Few authors are aware of this, but many 'Gold OA' fully open access journals outlets listed in DOAJ are not themselves immediately compliant with either Wellcome or UKRI licensing requirements. DOAJ lists 8,293 journals which use non-compliant licensing (CC BY-NC ; CC BY-NC-SA ; CC BY-NC-ND ) an author publishing in one of these outlets may need to choose "Route 2" (green OA) to comply with UKRI policy if one of these is chosen, but may not be aware of this at submission because the journal calls itself an "open access" journal. Hence using RRS-language at submission for all journal submissions is advisable to avoid problems and conflicts.

https://doaj.org/search/journals?ref=homepage-box&source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.license.exact%22%3A%5B%22CC%20BY-NC%22%2C%22CC%20BY-NC-SA%22%2C%22CC%20BY-NC-ND%22%5D%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22*%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%7D

**Comment by sje30** [comment]
Thjanks, noted.  I was not aware so many gold journals might fall short of the Wellcome/UKRI CC-BY requirements.
