### ISSUE TITLE
Is green OA always available?

### ISSUE THREAD

**Issue by rossmounce** [sje30/lse#5]
I think I also have to pull you up on this one before someone else does.

You write "green OA is always available".

This is only true under the assumption that the journals that people like to publish in remain subscription/'hybrid' journals.

For _fully_ open access APC-OA journals e.g. PLOS, eLife, Nature Communications (aside from rarely given fee waivers), they won't accept the article until an APC has been paid. At fully OA journals green OA does not exist and/or is not really available.

Thus I don't think it's strictly true to say "green OA is always available".  As long as publishers keep chosing to operate a predominately paywalled ('hybrid') model for a journal, then green OA is sort of always available. Even then, the publisher-imposed embargo policy may include a 24-month embargo on the AAM and may not allow CC BY on the AAM. The publisher/journal may also not allow/accept submissions with RRS-language. Some (all?) of the journals of the American Society of Hematology (ASH) e.g. _Blood_ are already known to not permit/accept manuscript submissions including RRS-language - they simply do not like or agree with CC BY licensing for research outputs.

**Comment by sje30** [comment]
Has _Blood_ gone on record about rejecting RRS?

And, I've assumed that any embargo periods from journals (e.g. Elsevier) are irrelevant -- doesn't the RRS allow you to ingore the embargo?
